
Resources:
  LogsGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /ecs/alex
        RetentionInDays: 14
  TaskRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      # Add policies as needed for your specific use case
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
  ExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::574134043875:policy/CFFULL
  SlipTask:
      Type: AWS::ECS::TaskDefinition
      Properties:
        RuntimePlatform:
          OperatingSystemFamily: LINUX
          CpuArchitecture: ARM64
        Family: alextask
        Cpu: 256
        Memory: 512
        EphemeralStorage:
          SizeInGiB: 21
        RequiresCompatibilities:
          - FARGATE
        NetworkMode: awsvpc
        ExecutionRoleArn: !GetAtt ExecutionRole.Arn
        TaskRoleArn: !GetAtt TaskRole.Arn
        ContainerDefinitions:
          - Name: alexcontainer
            Image: public.ecr.aws/m8l7i2c5/alexjonescatcher:latest
 
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref LogsGroup
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: ecs
            Essential: true
            Environment:
              - Name: AWS_REGION_T
                Value: !Ref AWS::Region
              - Name: completionCallbackUrl
                Value: "https://kxb72rqaei.execute-api.us-east-1.amazonaws.com/dev/RecordCompleteCallback"