service: griffin-autoscheduler-service



provider:
  name: aws
  memorySize: 128
  environment:
    AWS_REGION_T: !Ref AWS::Region
  



functions:
  checkSchedule:
    handler: src/checkSchedule.handler
    events:
      - schedule: rate(1 minute)