service: griffin-autoscheduler-service

provider:
  name: aws
  memorySize: 128
  environment:
    AWS_REGION_T: !Ref AWS::Region
    AUTO_RECORD_TABLE: !ImportValue RecordAutoRecordTable
    AGGREGATE_CURRENT_YOUTUBER_LIVE_TABLE: !ImportValue AggregateLiveTable

    AUTO_RECORD_TABLEArn: !ImportValue RecordAutoRecordTableArn
    AGGREGATE_CURRENT_YOUTUBER_LIVE_TABLEArn: !ImportValue AggregateLiveTableArn
    RECORD_REQUEST_TABLE: !ImportValue RecordRequestTable
    RECORD_RECORD_USERNAME_INDEX: !ImportValue RecordRequestUsernameIndexName
    RECORD_STATUS_TABLE: !ImportValue RecordStatusesTable
    RECORD_STATUS_TABLEArn: !ImportValue RecordStatusesTableArn


  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !ImportValue RecordAutoRecordTableArn
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !ImportValue AggregateLiveTableArn
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !ImportValue RecordRequestTableArn
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !ImportValue RecordRequestUsernameIndex
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !ImportValue RecordStatusesTableArn
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !ImportValue RecordStatusesFriendlyDateIndex
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !ImportValue RecordAutoRecordDateIndexArn
    - Effect: Allow
      Action:
        - cloudformation:*
      Resource: "*"
    - Effect: Allow
      Action:
        - ecs:*
      Resource: "*"
    - Effect: Allow
      Action:
        - iam:*
      Resource: "*"
  

functions:
  checkSchedule:
    handler: src/checkSchedule.handler
    timeout: 300
    events:
      - schedule: rate(1 minute)