
services:
  muxingservice:
    path: services/muxing
  
  autoscheduler:
    path: services/autoscheduler
    dependsOn:
      - record
      - liveChecker
      - recordRequests
    params:
      record_table_arn: ${record.RecordTableArn}
  
  liveChecker:
    path: services/liveChecker
    dependsOn:
      - ytdlp_layer
    params:
      recordCallBackUrl: ${record.ServiceEndpoint}/CallBackReceivedLiveEvents
      recordRequestTable: ${recordRequests.RecordRequestTable}
      recordRequestTableArn: ${recordRequests.RecordRequestTableArn}
      ytdlpArn: ${ytdlp_layer.YtdlpLambdaLayerQualifiedArn}
  
  recordRequests:
    path: services/recordRequests
  
  record:
    path: services/record
    params:
      recordRequestUrl: ${recordRequests.ServiceEndpoint}/recordRequest/
      recordRequestTable: ${recordRequests.RecordRequestTable}
  
  ytdlp_layer:
    path: services/ytdlp_layer