
services:

  utilitiesapi:
    path: services/utilitiesapi

  liveChecker:
    path: services/liveChecker
    params:
      recordCallBackUrl: ${record.ServiceEndpoint}/CallBackReceivedLiveEvents
  
  poobic:
    path: services/poobic

  recordRequests:
    path: services/recordRequests
  
  ecsEventsResource:
    path: services/ecsevents
    params:
      HandleEventsFromECSArn: ${recordRequests.HandleEventsFromECSLambdaFunctionQualifiedArn}

  
  record:
    path: services/record
    params:
      recordRequestUrl: ${recordRequests.ServiceEndpoint}/recordRequest/
      recordRequestTable: ${recordRequests.RecordRequestTable}
