service: youtube-downloader-service


provider:
  name: aws

resources:
  Resources:
    ProcessVideoDownloadQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ProcessVideoDownloadQueue
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600
        ReceiveMessageWaitTimeSeconds: 20
    YoutubeDownloaderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: YoutubeDownloaderTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


functions:
  MakeDownloadVideoRequest:
    handler: src/makedownloadvideorequest.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: /makeDownloadVideoRequest/{youtubeurl}
          method: post
          cors: true

  ProcessVideoDownload:
    handler: src/processvideodownload.handler
    memorySize: 256
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-1:574134043875:layer:ytdlp:10
      
       