service: griffin-record-service

provider:
  name: aws
  memorySize: 128
  environment:
    RECORD_TABLE: !Ref RecordTable
    RECORD_REQUEST_TABLE: !ImportValue RecordRequestTable
    AWS_REGION_T: !Ref AWS::Region
    RequestRequestTable: ${param:recordRequestTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - ecs:RunTask
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:574134043875:table/RecordRequestTable/index/username-index"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !ImportValue RecordRequestTableArn
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt RecordTable.Arn
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:574134043875:table/RecordTable/index/username-index"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:574134043875:table/RecordTable/index/record-request-id-index"
    - Effect: Allow
      Action:
        - cloudformation:*
      Resource: "*"

resources:
  Outputs:
    RecordBucket:
      Value: !Ref RecordInputBucket
      Export:
        Name: RecordInputBucket
  Resources:
    ECRRecordRepository:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: griffin-record
    EcsDownloadCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterName: griffin-record-cluster
    RecordInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: griffin-record-input
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - '*'
              MaxAge: 3000
    RecordTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RecordTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: recordrequestid
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: record-request-id-index
            KeySchema:
              - AttributeName: recordrequestid
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: username-index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

functions:
  RecordCompleteCallback:
    handler: completeCallback.handler
    events:
      - http:
          path: /RecordCompleteCallback
          method: post
          cors: true
  RecordByRequestIDAdhoc:
    handler: RecordByRequestIDAdhoc.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ecs:*
        Resource: "*"
    events:
      - http:
          path: /RecordByRequestIDAdhoc/{requestid}
          method: post
          cors: true
      
  CallBackReceivedLiveEvents:
    handler: CallBackReceivedLiveEvents.handler
    events:
      - http:
          path: /CallBackReceivedLiveEvents
          method: post
          cors: true