Parameters:
  Name:
    Type: String
    Default: griffin-record-1
  Image:
    Type: String
    Default: public.ecr.aws/m8l7i2c5/griffin:latest
  Channel:
    Type: String
    Default: "@LofiGirl"
  Timeout:
    Type: String
    Default: 60s
  CompletionCallbackUrl:
    Type: String
    Default: https://kxb72rqaei.execute-api.us-east-1.amazonaws.com/dev/RecordCompleteCallback

Resources:
  LogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${Name}
      RetentionInDays: 14
  
  ECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref Name
          Image: !Ref Image
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: AWS_REGION_T
              Value: !Ref AWS::Region
            - Name: channel
              Value: !Ref Channel
            - Name: timeout
              Value: !Ref Timeout
            - Name: stackname
              Value: !Ref AWS::StackName
            - Name: completionCallbackUrl
              Value: !Ref CompletionCallbackUrl

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      # Add policies as needed for your specific use case
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess


Outputs:
  ECSTASKName:
    Value: !Ref ECSTask