service: griffin-util-service


provider:
  name: aws
  memorySize: 128



# layers:
#   ytdlp:
#     path: ./yt-dlp_linux
#     description: youtube-dlp
#     compatibleRuntimes:
#       - nodejs12.x
#       - nodejs14.x
#       - nodejs16.x
#       - nodejs18.x
#     licenseInfo: MIT

functions:
  GetLiveIndex:
    handler: src/getliveindex.handler
    memorySize: 256
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-1:574134043875:layer:ytdlp:10
    events:
      - http:
          path: /getLiveIndex/{youtubeurl}
          method: post
plugins:
  - serverless-prune-plugin


custom:
  prune:
    automatic: true
    number: 3