service: griffin-poobic-service


provider:
  name: aws
  memorySize: 128


functions:
  callbackGriffinIsLive:
    handler: callbackGriffinIsLive.handler
    events:
      - http:
          path: /callbackGriffinIsLive
          method: post