apiVersion: v1
clusters:
- name: "k8s-zealous-moore"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXhOekEyTkRRME4xb1hEVE16TURReE56QTJORFEwTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk92CjAwaE1ndjh2QzNxN1dMRnZLaEJKaS9mVjRrNFFqYTNhMlhpc1dnWnpqUE15bFZROGk0RVRCTHdtVmI0eGdsVmgKVDE3aWE1c0Q0dytseHF1SWxvNUswTVBQaW5hd2VxSUkyYVp6THhOdUFKTS9JeHA1K1JSaEo0NWxIcVFaYWZOWQpEUkh3Zm91elFGZWlLUVZOcFNTMEdJL0xLNjJmQ3M4Qm1NaVdpTHpDWE93UkZhRDlLYnNHUjJZMldic0g3VGY3CnVHV3I0MWxtTmVYbnZMQTlvRmE0OUNpV01lb29kaFNHMGJPc252YzMwQWdGQmY5cm9ubUJlN3MxT1lpSDNqdlAKU1dwT3Y5WlovMTFyQjE2T3dRekF4bjh5QjUrNEZDUlh3cFlrTGhJdGFkOFZGU3Fad241ZEt5TlIwUElpK3F2QgovM1daYjhGQk8vQksrMVUyeUFVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCbUNhL05USWNqaUkyU0NGbjNXaFM5Z3Y4L0hNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDTy9IemdtdmROMG1zNmhsSGdhQlJpWXBxN1A5ZWtpUUFBQ21NT3ZpVjNQKzRmWDgrdgovTVZ0Q0VMdHJBKzdydUUxclJNNFpzWXRnbDB0dm0xR2JuUU5jSUM3b3BjMmdpNUhhaENiRG1ZQTEvT0NBbXgwCjRIQjg4L0JSS0dlK3BFM3F1RWhoTERsUVJCZGoyOUpqU0dFeXVDc0U3SWdvSHBrRnlKckhNL21icnJ4clJ5UkoKR281L2l0eFU0TnROMWdlWGVoV2tkZDQ2TFZodGZPMktRR1NiUDU0eWVBRG1EWGhkUVZLYUkzQVc5NjgwcTNxNgppc1o3RVBySzgrQ0RpSkFSUXJxdzRBSEY2TnlmWVpnUW5VZ0xpTENrVXVFcXRWbDF1QkZ3TUFsN3FMa1FQcDkyCjZiZkVmMm40ckxoVUhXZ1VKT2p6UlZnNHpYNmFQaGphSjJONgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://53d08274-d850-45d6-9da2-056ffc8af44e.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@k8s-zealous-moore
  context:
    cluster: "k8s-zealous-moore"
    user: k8s-zealous-moore-admin
current-context: admin@k8s-zealous-moore
kind: Config
preferences: {}
users:
- name: k8s-zealous-moore-admin
  user:
    token: mcqxpGlm1VoNOu1TxoERPG2ZvIV74ItC6mU0v1z9u68z0l2iWGXQnYD6