service: reports-poobic-service



provider:
  name: aws
  runtime: nodejs18.x
  environment:
    AWS_REGION_T: !Ref AWS::Region
    CLUSTER_NAME: griffin-record-cluster
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ecs:*
      Resource: "*"



functions:
  getAllEcsRunning:
    handler: src/getAllEcsTasksRunning.handler
    events:
      - http:
          path: /getAllEcsRunning
          method: get
          cors: true
plugins:
  - serverless-prune-plugin
